# Generated by Django 3.2.5 on 2021-07-29 06:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='centerstone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stone', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='colorofcstone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='companyinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('company_name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('mobile_no', models.CharField(max_length=20)),
                ('tel_no', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.EmailField(max_length=150)),
                ('pan_no', models.CharField(max_length=20)),
                ('GST_no', models.CharField(max_length=20)),
                ('line_id', models.CharField(max_length=20)),
                ('wechat_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='gemtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gem', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='jewell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jewel', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Ko',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currncy', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='loc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='metal1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metal', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='shape1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='POJ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('stockid', models.CharField(blank=True, max_length=30)),
                ('grosswt', models.BigIntegerField()),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('pieces', models.BigIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('discount', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tag_price', models.BigIntegerField()),
                ('rate', models.IntegerField()),
                ('center_stone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.centerstone')),
                ('cert', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.certificate')),
                ('color_of_center_stone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.colorofcstone')),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.companyinfo')),
                ('currencyid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.ko')),
                ('jewellery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.jewell')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.loc')),
                ('metal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.metal1')),
                ('shape', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.shape1')),
            ],
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.countries'),
        ),
    ]
