# Generated by Django 3.2.5 on 2021-07-29 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='currencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=30)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.countries')),
            ],
        ),
        migrations.AlterField(
            model_name='poj',
            name='currencyid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.currencies'),
        ),
        migrations.DeleteModel(
            name='Ko',
        ),
    ]
