# Generated by Django 3.0.5 on 2021-12-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesofdiamond',
            name='units',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
