# Generated by Django 3.0.5 on 2021-12-01 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_auto_20211201_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='clonePurchaseOfColorStones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('Clarity', models.CharField(blank=True, max_length=30, null=True)),
                ('certificate_no', models.CharField(blank=True, max_length=30, null=True, verbose_name='Certificate Number')),
                ('measurements', models.CharField(blank=True, max_length=30, null=True)),
                ('PCS', models.IntegerField()),
                ('Weight', models.FloatField(null=True)),
                ('Price', models.FloatField()),
                ('units', models.CharField(blank=True, max_length=30, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('discount', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('total_val', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('purchaseapv', models.BooleanField(default=False)),
                ('tag_price', models.FloatField()),
                ('rate', models.FloatField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, default='', max_length=3000, null=True)),
                ('Treatment', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.Treatment_cs')),
                ('colour', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.color_of_colorstone')),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.companyinfo')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.currencies')),
                ('gem_type', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.gemtype')),
                ('lab', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.Lab_cs')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.location')),
                ('origin', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.Origin_cs')),
                ('shape', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.shape_cs')),
            ],
        ),
    ]
