# Generated by Django 3.0.5 on 2022-01-07 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_auto_20220107_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewel_media',
            name='jewel_object',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='media', serialize=False, to='firstapp.Inventoryofjewellery'),
        ),
    ]
