# Generated by Django 3.2.5 on 2021-07-29 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_auto_20210729_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poj',
            name='center_stone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.centerstone'),
        ),
        migrations.AlterField(
            model_name='poj',
            name='cert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.certificate'),
        ),
        migrations.AlterField(
            model_name='poj',
            name='color_of_center_stone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.colorofcstone'),
        ),
        migrations.AlterField(
            model_name='poj',
            name='company_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.companyinfo'),
        ),
        migrations.AlterField(
            model_name='poj',
            name='currencyid',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.currencies'),
        ),
        migrations.AlterField(
            model_name='poj',
            name='jewellery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.jewell'),
        ),
        migrations.AlterField(
            model_name='poj',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.loc'),
        ),
        migrations.AlterField(
            model_name='poj',
            name='metal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.metal1'),
        ),
    ]
