# Generated by Django 3.2.5 on 2021-07-29 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_auto_20210729_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poj',
            name='currencyid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.currencies'),
        ),
    ]
