# Generated by Django 3.0.5 on 2021-12-01 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_clonepurchaseofcolorstones'),
    ]

    operations = [
        migrations.CreateModel(
            name='clonePOJ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('center_stone_weight', models.DecimalField(decimal_places=2, max_digits=9)),
                ('center_stone_pieces', models.BigIntegerField()),
                ('grosswt', models.DecimalField(decimal_places=2, max_digits=9)),
                ('pcs', models.BigIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=9)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=9)),
                ('purchase_approval', models.BooleanField(default=False)),
                ('tag_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=9)),
                ('comment', models.TextField(blank=True, max_length=3000, null=True)),
                ('center_stone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.centerstone')),
                ('cert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.certificate')),
                ('color_of_center_stone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.colorofcstone')),
                ('company_name', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.companyinfo')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.currencies')),
                ('jewellery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.jewell')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.location')),
                ('metal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.metal1')),
                ('shape', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.shape1')),
            ],
        ),
    ]
