# Generated by Django 3.0.5 on 2022-01-07 07:49

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_auto_20220107_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorstone_media',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
