# Generated by Django 3.2.5 on 2021-07-30 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_alter_poj_currencyid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_stone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.centerstone')),
                ('shape', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.shape1')),
            ],
        ),
    ]
