# Generated by Django 3.0.5 on 2022-01-07 07:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_auto_20220107_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorstone_media',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
