# Generated by Django 3.0.5 on 2021-12-02 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_clonepoj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloneinvofdiamond',
            name='laser_inscription',
            field=models.BooleanField(default=False),
        ),
    ]
