# Generated by Django 3.2.5 on 2021-07-30 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='poj',
            name='total_val_j',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='poj',
            name='rate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='poj',
            name='tag_price',
            field=models.FloatField(),
        ),
    ]
