# Generated by Django 3.0.5 on 2022-01-07 08:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_auto_20220107_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorstone_media',
            name='colorstone_info',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Colour Stone Information'),
        ),
    ]
