# Generated by Django 3.0.5 on 2022-01-08 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_auto_20220107_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centerstone',
            name='stone',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='cert',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='certificate_d',
            name='certd',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='clarity',
            name='clarity',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='color_of_colorstone',
            name='color',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='color_origin',
            name='c_o',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='colorofcstone',
            name='color',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='company_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='countries',
            name='country',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='currencies',
            name='currency',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='cut',
            name='cut',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='fancy_color_intensity',
            name='f_c_i',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='fancycolor_grade',
            name='f_c_grade',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='fluorescence_color',
            name='f_color',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='fluorescence_intensity',
            name='f_intensity',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='jewell',
            name='jewel',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='lab_cs',
            name='lab',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='place',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='origin_cs',
            name='org',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='polish',
            name='polish',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='shape1',
            name='shape',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='shape_cs',
            name='shape',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='shape_d',
            name='shape',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='symmetry',
            name='symmetry',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='treatment_cs',
            name='treatment',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='white_color_grade',
            name='w_c_g',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
