# Generated by Django 3.2.9 on 2021-12-02 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_auto_20211203_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryofdiamond',
            name='frontend',
            field=models.BooleanField(default=False),
        ),
    ]
