# Generated by Django 3.0.5 on 2022-01-09 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_auto_20220108_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diamond_media',
            old_name='Diamond_object',
            new_name='stockid',
        ),
        migrations.RenameField(
            model_name='jewel_media',
            old_name='jewel_object',
            new_name='stockid',
        ),
        migrations.AddField(
            model_name='salesreturn',
            name='currency',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesreturn_cs',
            name='currency',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesreturn_cs',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='salesreturn_d',
            name='currency',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesreturn_d',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='cloneinvofcolorstones',
            name='Weight_cs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='clonepurchaseofcolorstones',
            name='Price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='clonepurchaseofcolorstones',
            name='Weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseofcolorstones',
            name='Price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseofcolorstones',
            name='Weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
