# Generated by Django 3.2.5 on 2021-08-01 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_alter_poj_total_val_j'),
    ]

    operations = [
        migrations.CreateModel(
            name='certificate_no_cs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='color_cs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Inventoryofcolorstones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockid', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('shape', models.CharField(max_length=30)),
                ('gem_type', models.CharField(max_length=30)),
                ('weight', models.IntegerField()),
                ('origin', models.CharField(max_length=30)),
                ('treatment', models.CharField(max_length=30)),
                ('certificate_no_cs', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('measurements', models.FloatField()),
                ('lab', models.CharField(max_length=30)),
                ('tag_price_cs', models.FloatField()),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Lab_cs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='measurements_cs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Origin_cs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='shape_cs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Treatment_cs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treat', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='weight_cs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOfColorStones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('stockid_cs', models.CharField(max_length=30)),
                ('Clarity', models.CharField(max_length=30)),
                ('colour', models.CharField(max_length=30)),
                ('measurements', models.IntegerField()),
                ('PCS', models.IntegerField()),
                ('Weight_cs', models.FloatField()),
                ('Price', models.FloatField()),
                ('units', models.IntegerField()),
                ('amount', models.FloatField()),
                ('DIS', models.FloatField()),
                ('DIS_amount', models.FloatField()),
                ('Total_value_c_s', models.FloatField()),
                ('tag_price_cs', models.FloatField()),
                ('rate', models.FloatField()),
                ('Treatment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.treatment_cs')),
                ('certificate_no_cs', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.certificate_no_cs')),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.companyinfo')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.currencies')),
                ('gem_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.gemtype')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.lab_cs')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.loc')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.origin_cs')),
                ('shape', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.shape_cs')),
            ],
        ),
    ]
