# Generated by Django 3.2.5 on 2021-08-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0008_certificate_no_cs_color_cs_inventoryofcolorstones_lab_cs_measurements_cs_origin_cs_purchaseofcolorst'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseofcolorstones',
            name='DIS',
        ),
        migrations.RemoveField(
            model_name='purchaseofcolorstones',
            name='DIS_amount',
        ),
        migrations.RemoveField(
            model_name='purchaseofcolorstones',
            name='Total_value_c_s',
        ),
        migrations.AddField(
            model_name='purchaseofcolorstones',
            name='discount',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseofcolorstones',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='purchaseofcolorstones',
            name='total_val_cs',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=9),
            preserve_default=False,
        ),
    ]
