# Generated by Django 3.0.5 on 2021-12-03 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0008_auto_20211203_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diamond_media',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='Certificates/Diamond/'),
        ),
        migrations.AlterField(
            model_name='diamond_media',
            name='jewellery_info',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Diamond Information'),
        ),
        migrations.AlterField(
            model_name='jewel_media',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='Certificates/Jewellery/'),
        ),
        migrations.AlterField(
            model_name='jewel_media',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='JewelleryMedia/'),
        ),
        migrations.AlterField(
            model_name='jewel_media',
            name='image10',
            field=models.ImageField(blank=True, null=True, upload_to='JewelleryMedia/'),
        ),
        migrations.AlterField(
            model_name='jewel_media',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='JewelleryMedia/'),
        ),
        migrations.AlterField(
            model_name='jewel_media',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='JewelleryMedia/'),
        ),
        migrations.AlterField(
            model_name='jewel_media',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='JewelleryMedia/'),
        ),
        migrations.AlterField(
            model_name='jewel_media',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='JewelleryMedia/'),
        ),
        migrations.AlterField(
            model_name='jewel_media',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='JewelleryMedia/'),
        ),
        migrations.AlterField(
            model_name='jewel_media',
            name='image7',
            field=models.ImageField(blank=True, null=True, upload_to='JewelleryMedia/'),
        ),
        migrations.AlterField(
            model_name='jewel_media',
            name='image8',
            field=models.ImageField(blank=True, null=True, upload_to='JewelleryMedia/'),
        ),
        migrations.AlterField(
            model_name='jewel_media',
            name='image9',
            field=models.ImageField(blank=True, null=True, upload_to='JewelleryMedia/'),
        ),
        migrations.AlterField(
            model_name='jewel_media',
            name='jewellery_info',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Jewellery Information'),
        ),
    ]
