# Generated by Django 3.0.5 on 2022-01-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0008_auto_20220109_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreturn',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='salesreturn',
            name='center_stone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
