# Generated by Django 3.0.5 on 2022-01-12 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0009_auto_20220109_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesreturn',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='salesreturn',
            name='center_stone',
        ),
    ]
