# Generated by Django 3.2.5 on 2021-08-01 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0009_auto_20210801_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseofcolorstones',
            name='Treatment',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.treatment_cs'),
        ),
        migrations.AlterField(
            model_name='purchaseofcolorstones',
            name='gem_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.gemtype'),
        ),
        migrations.AlterField(
            model_name='purchaseofcolorstones',
            name='lab',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.lab_cs'),
        ),
        migrations.AlterField(
            model_name='purchaseofcolorstones',
            name='origin',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.origin_cs'),
        ),
        migrations.AlterField(
            model_name='purchaseofcolorstones',
            name='shape',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.shape_cs'),
        ),
        migrations.AlterField(
            model_name='purchaseofcolorstones',
            name='stockid_cs',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
