# Generated by Django 3.0.5 on 2022-01-13 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0010_auto_20220112_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poj',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='firstapp.location'),
            preserve_default=False,
        ),
    ]
