# Generated by Django 3.2.5 on 2021-08-01 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0010_auto_20210801_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseofcolorstones',
            name='certificate_no_cs',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.certificate_no_cs'),
        ),
    ]
