# Generated by Django 3.0.5 on 2021-12-04 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0011_auto_20211203_1919'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate_d',
            options={'verbose_name_plural': 'Diamond - Certificates Types'},
        ),
        migrations.AlterModelOptions(
            name='clarity',
            options={'verbose_name_plural': 'Diamond - Clarity'},
        ),
        migrations.AlterModelOptions(
            name='cloneinvofcolorstones',
            options={'verbose_name_plural': 'ColourStone - Cart'},
        ),
        migrations.AlterModelOptions(
            name='cloneinvofdiamond',
            options={'verbose_name_plural': 'Diamond - Cart'},
        ),
        migrations.AlterModelOptions(
            name='cloneinvofjewellery',
            options={'verbose_name_plural': 'Jewellery - Cart'},
        ),
        migrations.AlterModelOptions(
            name='cut',
            options={'verbose_name_plural': 'Diamond - Cuts'},
        ),
        migrations.AlterModelOptions(
            name='fancy_color_intensity',
            options={'verbose_name_plural': 'Diamond - Fancy Color Intensities'},
        ),
        migrations.AlterModelOptions(
            name='fancycolor_grade',
            options={'verbose_name_plural': 'Diamond - Fancy Colour Grades'},
        ),
        migrations.AlterModelOptions(
            name='fluorescence_color',
            options={'verbose_name_plural': 'Diamond - Fluorescence Colours'},
        ),
        migrations.AlterModelOptions(
            name='fluorescence_intensity',
            options={'verbose_name_plural': 'Diamond - Fluorescence Intensities'},
        ),
        migrations.AlterModelOptions(
            name='inventoryofcolorstones',
            options={'verbose_name_plural': 'ColourStone - Inventory'},
        ),
        migrations.AlterModelOptions(
            name='inventoryofdiamond',
            options={'verbose_name_plural': 'Diamond - Inventory'},
        ),
        migrations.AlterModelOptions(
            name='inventoryofjewellery',
            options={'verbose_name_plural': 'Jewellery - Inventory'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name_plural': 'Locations'},
        ),
        migrations.AlterModelOptions(
            name='pod',
            options={'verbose_name_plural': 'Diamond - Purchase'},
        ),
        migrations.AlterModelOptions(
            name='poj',
            options={'verbose_name_plural': 'Jewellery - Purchases'},
        ),
        migrations.AlterModelOptions(
            name='polish',
            options={'verbose_name_plural': 'Diamond - Polishes'},
        ),
        migrations.AlterModelOptions(
            name='purchaseofcolorstones',
            options={'verbose_name_plural': 'ColourStone - Purchase'},
        ),
        migrations.AlterModelOptions(
            name='salesofdiamond',
            options={'verbose_name_plural': 'Diamond - Sales'},
        ),
        migrations.AlterModelOptions(
            name='salesreturn',
            options={'verbose_name_plural': 'Jewellery - Sales Return'},
        ),
        migrations.AlterModelOptions(
            name='salesreturn_cs',
            options={'verbose_name_plural': 'ColourStone - Sales Return'},
        ),
        migrations.AlterModelOptions(
            name='salesreturn_d',
            options={'verbose_name_plural': 'Diamond - Sales Return'},
        ),
        migrations.AlterModelOptions(
            name='shape_d',
            options={'verbose_name_plural': 'Diamond - Shapes'},
        ),
        migrations.AlterModelOptions(
            name='symmetry',
            options={'verbose_name_plural': 'Diamond - Symmetries'},
        ),
        migrations.AlterModelOptions(
            name='white_color_grade',
            options={'verbose_name_plural': 'Diamond - White Colour Grades'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='centerstone',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='certificate_d',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='clarity',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cloneinvofcolorstones',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cloneinvofdiamond',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cloneinvofjewellery',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='clonepod',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='clonepoj',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='clonepurchaseofcolorstones',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='color_of_colorstone',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='color_origin',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='colorofcstone',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='colorstone_media',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='countries',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='currencies',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cut',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='diamond_media',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fancy_color_intensity',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fancycolor_grade',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fluorescence_color',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fluorescence_intensity',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='gemtype',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='inventoryofcolorstones',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='inventoryofdiamond',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='inventoryofjewellery',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='jewel_media',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='jewell',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lab_cs',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='metal1',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='origin_cs',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pod',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='poj',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='polish',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='purchaseofcolorstones',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='salesofcolorstones',
            name='DIS_amount_cs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='DISCOUNT Amount'),
        ),
        migrations.AlterField(
            model_name='salesofcolorstones',
            name='DIS_cs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Discount %'),
        ),
        migrations.AlterField(
            model_name='salesofcolorstones',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.color_of_colorstone', verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='salesofcolorstones',
            name='company_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.companyinfo', verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='salesofcolorstones',
            name='gem_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.gemtype', verbose_name='Gem Type'),
        ),
        migrations.AlterField(
            model_name='salesofcolorstones',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='salesofcolorstones',
            name='lab',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.Lab_cs', verbose_name='Lab'),
        ),
        migrations.AlterField(
            model_name='salesofcolorstones',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.location', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='salesofcolorstones',
            name='origin',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.Origin_cs', verbose_name='Origin'),
        ),
        migrations.AlterField(
            model_name='salesofcolorstones',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='salesofcolorstones',
            name='shape',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.shape_cs', verbose_name='Shape'),
        ),
        migrations.AlterField(
            model_name='salesofcolorstones',
            name='stockid',
            field=models.CharField(max_length=30, verbose_name='Stock ID'),
        ),
        migrations.AlterField(
            model_name='salesofcolorstones',
            name='treatment',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.Treatment_cs', verbose_name='Treatment'),
        ),
        migrations.AlterField(
            model_name='salesofcolorstones',
            name='units_cs',
            field=models.CharField(default='', max_length=30, verbose_name='Units'),
        ),
        migrations.AlterField(
            model_name='salesofdiamond',
            name='DIS_Amount_d',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='DISCOUNT Amount'),
        ),
        migrations.AlterField(
            model_name='salesofdiamond',
            name='DIS_d',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Discount %'),
        ),
        migrations.AlterField(
            model_name='salesofdiamond',
            name='PCS_d',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pieces'),
        ),
        migrations.AlterField(
            model_name='salesofdiamond',
            name='amount_d',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='salesofdiamond',
            name='certificate_d',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.certificate_d', verbose_name='Certificate Type'),
        ),
        migrations.AlterField(
            model_name='salesofdiamond',
            name='certificate_no_d',
            field=models.CharField(max_length=30, verbose_name='Certificate No.'),
        ),
        migrations.AlterField(
            model_name='salesofdiamond',
            name='clarity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.clarity', verbose_name='Clarity'),
        ),
        migrations.AlterField(
            model_name='salesofdiamond',
            name='color_origin1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.color_origin', verbose_name='Colour origin'),
        ),
        migrations.AlterField(
            model_name='salesofdiamond',
            name='comment',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='salesofdiamond',
            name='company_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.companyinfo', verbose_name='Company name'),
        ),
        migrations.AlterField(
            model_name='salesofdiamond',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.currencies', verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='salesofdiamond',
            name='cut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.cut', verbose_name='Cut'),
        ),
        migrations.AlterField(
            model_name='salesofdiamond',
            name='depth',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Depth'),
        ),
        migrations.AlterField(
            model_name='salesofdiamond',
            name='fancycolor_grade',
            field=models.CharField(max_length=30, verbose_name='Fancy Color Grade'),
        ),
        migrations.AlterField(
            model_name='salesofdiamond',
            name='fluorescence_color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.fluorescence_color', verbose_name='Fluorescence Color'),
        ),
        migrations.AlterField(
            model_name='salesofdiamond',
            name='fluorescence_intensity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.fluorescence_intensity', verbose_name='Fluorescence Intensity'),
        ),
        migrations.AlterField(
            model_name='salesofdiamond',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='salesofdiamond',
            name='laser_inscription',
            field=models.BooleanField(default=False, verbose_name='Laser Inscription'),
        ),
        migrations.AlterField(
            model_name='salesofdiamond',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.location', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='salesofdiamond',
            name='measurements',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Measurements'),
        ),
        migrations.AlterField(
            model_name='salesofdiamond',
            name='polish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.polish', verbose_name='Polish'),
        ),
        migrations.AlterField(
            model_name='salesofdiamond',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='salesofdiamond',
            name='rate_d',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Rate'),
        ),
        migrations.AlterField(
            model_name='salesofdiamond',
            name='salesapprovalstatus_d',
            field=models.BooleanField(default=False, verbose_name='Sold'),
        ),
        migrations.AlterField(
            model_name='salesofdiamond',
            name='shape',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.shape_d', verbose_name='Shape'),
        ),
        migrations.AlterField(
            model_name='salesofdiamond',
            name='stockid',
            field=models.CharField(max_length=30, verbose_name='Stock ID'),
        ),
        migrations.AlterField(
            model_name='salesofdiamond',
            name='symmetry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.symmetry', verbose_name='Symmetry'),
        ),
        migrations.AlterField(
            model_name='salesofdiamond',
            name='table',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Table'),
        ),
        migrations.AlterField(
            model_name='salesofdiamond',
            name='tag_price_d',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Tag Price'),
        ),
        migrations.AlterField(
            model_name='salesofdiamond',
            name='total_value_d',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Total Value'),
        ),
        migrations.AlterField(
            model_name='salesofdiamond',
            name='units',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Units'),
        ),
        migrations.AlterField(
            model_name='salesofdiamond',
            name='weight_d',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='salesofdiamond',
            name='white_color_grade1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.white_color_grade', verbose_name='White Colour Grade'),
        ),
        migrations.AlterField(
            model_name='salesofjewellery',
            name='DIS',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, verbose_name='Discount %'),
        ),
        migrations.AlterField(
            model_name='salesofjewellery',
            name='DIS_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, verbose_name='DISCOUNT Amount'),
        ),
        migrations.AlterField(
            model_name='salesofjewellery',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='salesofjewellery',
            name='center_stone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.centerstone', verbose_name='Center Stone'),
        ),
        migrations.AlterField(
            model_name='salesofjewellery',
            name='center_stone_pieces',
            field=models.BigIntegerField(verbose_name='Center Stone Pieces'),
        ),
        migrations.AlterField(
            model_name='salesofjewellery',
            name='center_stone_weight',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Center Stone Weight'),
        ),
        migrations.AlterField(
            model_name='salesofjewellery',
            name='certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.certificate', verbose_name='Certificate Type'),
        ),
        migrations.AlterField(
            model_name='salesofjewellery',
            name='color_of_center_stone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.colorofcstone', verbose_name='Colour of Center Stone'),
        ),
        migrations.AlterField(
            model_name='salesofjewellery',
            name='comment',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='salesofjewellery',
            name='company_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.companyinfo', verbose_name='Company name'),
        ),
        migrations.AlterField(
            model_name='salesofjewellery',
            name='gross_wt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, verbose_name='Gross Weight'),
        ),
        migrations.AlterField(
            model_name='salesofjewellery',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='salesofjewellery',
            name='jewellery_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.jewell', verbose_name='Jewellery Type'),
        ),
        migrations.AlterField(
            model_name='salesofjewellery',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.location', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='salesofjewellery',
            name='metal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.metal1', verbose_name='Metal'),
        ),
        migrations.AlterField(
            model_name='salesofjewellery',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, verbose_name='Rate'),
        ),
        migrations.AlterField(
            model_name='salesofjewellery',
            name='salesapprovalstatus',
            field=models.BooleanField(default=False, verbose_name='Sold'),
        ),
        migrations.AlterField(
            model_name='salesofjewellery',
            name='shape',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.shape1', verbose_name='Shape'),
        ),
        migrations.AlterField(
            model_name='salesofjewellery',
            name='stockid',
            field=models.CharField(max_length=30, verbose_name='Stock ID'),
        ),
        migrations.AlterField(
            model_name='salesofjewellery',
            name='tag_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, verbose_name='Tag Price'),
        ),
        migrations.AlterField(
            model_name='salesofjewellery',
            name='total_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, verbose_name='Total Value'),
        ),
        migrations.AlterField(
            model_name='salesreturn',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='salesreturn_cs',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='salesreturn_d',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='shape1',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='shape_cs',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='shape_d',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='state',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='symmetry',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='treatment_cs',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='white_color_grade',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
