# Generated by Django 3.0.5 on 2022-01-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0012_auto_20220113_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='tel_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
