# Generated by Django 3.0.5 on 2021-12-04 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0012_auto_20211204_1050'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_table',
        ),
    ]
