# Generated by Django 3.0.5 on 2021-12-04 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0013_delete_user_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='State',
        ),
    ]
