# Generated by Django 3.2.5 on 2021-08-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0013_auto_20210801_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventoryofjewellery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockid', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('jewellery_type', models.CharField(max_length=30)),
                ('centre_stone', models.CharField(max_length=30)),
                ('color_centre_stone', models.CharField(max_length=30)),
                ('shape', models.CharField(max_length=30)),
                ('metal', models.CharField(max_length=30)),
                ('gross_weight', models.FloatField()),
                ('certificate', models.CharField(max_length=30)),
                ('pcs', models.IntegerField()),
                ('tag_price', models.FloatField()),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='poj',
            name='grosswt',
            field=models.FloatField(),
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
