# Generated by Django 3.2.5 on 2021-08-02 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0014_auto_20210802_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryofjewellery',
            name='stockid',
        ),
        migrations.RemoveField(
            model_name='poj',
            name='stockid',
        ),
    ]
