# Generated by Django 3.2.5 on 2021-08-02 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0015_auto_20210802_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryofjewellery',
            old_name='certificate',
            new_name='cert',
        ),
        migrations.RenameField(
            model_name='inventoryofjewellery',
            old_name='gross_weight',
            new_name='grosswt',
        ),
        migrations.RenameField(
            model_name='poj',
            old_name='pieces',
            new_name='pcs',
        ),
    ]
