# Generated by Django 3.2.5 on 2021-08-02 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0016_auto_20210802_2002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryofjewellery',
            old_name='color_centre_stone',
            new_name='color_of_centre_stone',
        ),
    ]
