# Generated by Django 3.2.9 on 2021-12-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0017_auto_20211208_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreturn_cs',
            name='clarity',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
