# Generated by Django 3.2.5 on 2021-08-02 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0017_rename_color_centre_stone_inventoryofjewellery_color_of_centre_stone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryofjewellery',
            old_name='color_of_centre_stone',
            new_name='color_of_center_stone',
        ),
    ]
