# Generated by Django 3.2.5 on 2021-08-02 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0018_rename_color_of_centre_stone_inventoryofjewellery_color_of_center_stone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryofjewellery',
            old_name='centre_stone',
            new_name='center_stone',
        ),
    ]
