# Generated by Django 3.2.5 on 2021-08-02 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0019_rename_centre_stone_inventoryofjewellery_center_stone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryofjewellery',
            name='status',
        ),
    ]
