# Generated by Django 3.2.5 on 2021-08-04 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0020_remove_inventoryofjewellery_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='amount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='certificate_d',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certd', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='certificate_no',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='certificate_no_d',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_no_d', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='clarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clarity', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='color_origin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_o', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='cut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cut', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='depths',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DIS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dis', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DIS_amount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='fancy_color_intensity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_c_i', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='fancy_colour_grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fancy_color_grade', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='fancycolor1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_color1', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='fancycolor2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_color2', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='fancycolor_grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_c_grade', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='fluorescence_color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_color', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='fluorescence_intensity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_intensity', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Inventoryofdiamond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockid', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('shape', models.CharField(max_length=30)),
                ('clarity', models.CharField(max_length=30)),
                ('white_color_grade', models.CharField(max_length=30)),
                ('fancy_color_intensity', models.CharField(max_length=30)),
                ('fancy_color_grade', models.CharField(max_length=30)),
                ('weight', models.IntegerField()),
                ('cut', models.CharField(max_length=30)),
                ('polish', models.CharField(max_length=30)),
                ('symmetry', models.CharField(max_length=30)),
                ('measurements', models.FloatField()),
                ('depth', models.CharField(max_length=30)),
                ('table', models.CharField(max_length=30)),
                ('fluorescence_intensity', models.CharField(max_length=30)),
                ('fluorescence_color', models.CharField(max_length=30)),
                ('certicate_number', models.CharField(max_length=30)),
                ('certificate', models.CharField(max_length=30)),
                ('laser_inscription', models.CharField(max_length=30)),
                ('pcs', models.IntegerField()),
                ('tag_price', models.FloatField()),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='laser_inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laser_inscription', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='laser_inscription_d',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laser_inscription_d', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='measurement_d',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_d', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='measurements_d',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurements', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='overtone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('over_t', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PCS_d',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PCS', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='polish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polish', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='rate_d',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_d', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='shape_d',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='symmetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symmetry', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='tag_price_d',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='total_value_d',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='weight_d',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_d', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='white_color_grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_c_g', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='POD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('stockid_d', models.CharField(max_length=30)),
                ('measurements', models.IntegerField()),
                ('depth', models.IntegerField()),
                ('table_perc', models.IntegerField()),
                ('certificate_no', models.CharField(max_length=30)),
                ('laser_inscription', models.BooleanField()),
                ('PCS_d', models.IntegerField()),
                ('weight_d', models.FloatField()),
                ('price', models.FloatField()),
                ('units', models.IntegerField()),
                ('amount_d', models.DecimalField(decimal_places=2, max_digits=9)),
                ('DIS_d', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('DIS_Amount', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('total_val_d', models.FloatField()),
                ('tag_price_d', models.FloatField()),
                ('rate_d', models.FloatField()),
                ('certificate_d', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.certificate_d')),
                ('clarity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.clarity')),
                ('color_origin1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.color_origin')),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.companyinfo')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.currencies')),
                ('cut', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.cut')),
                ('fancy_color_intensity1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.fancy_color_intensity')),
                ('fancycolor1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.fancycolor1')),
                ('fancycolor2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.fancycolor2')),
                ('fancycolor_grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.fancycolor_grade')),
                ('fluorescence_color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.fluorescence_color')),
                ('fluorescence_intensity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.fluorescence_intensity')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.loc')),
                ('overtone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.overtone')),
                ('polish', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.polish')),
                ('shape', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.shape_d')),
                ('symmetry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.symmetry')),
                ('white_color_grade1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.white_color_grade')),
            ],
        ),
    ]
