# Generated by Django 3.0.5 on 2021-12-09 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0021_auto_20211209_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clonepurchaseofcolorstones',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
