# Generated by Django 3.2.5 on 2021-08-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0022_auto_20210804_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryofjewellery',
            name='stockid',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='poj',
            name='stockid',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
