# Generated by Django 3.2.5 on 2021-08-04 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0023_auto_20210804_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryofjewellery',
            name='stockid',
            field=models.CharField(blank=True, default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='poj',
            name='stockid',
            field=models.CharField(blank=True, default=1, max_length=30),
            preserve_default=False,
        ),
    ]
