# Generated by Django 3.2.9 on 2021-12-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0023_auto_20211230_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clonepurchaseofcolorstones',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='clonepurchaseofcolorstones',
            name='tag_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryofcolorstones',
            name='tag_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
