# Generated by Django 3.2.5 on 2021-08-05 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0024_auto_20210804_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poj',
            name='stockid',
        ),
    ]
