# Generated by Django 3.2.9 on 2021-12-30 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0024_auto_20211230_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloneinvofdiamond',
            name='white_color_grade1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.white_color_grade'),
        ),
    ]
