# Generated by Django 3.2.5 on 2021-08-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0025_remove_poj_stockid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryofdiamond',
            old_name='pcs',
            new_name='PCS',
        ),
        migrations.RenameField(
            model_name='inventoryofdiamond',
            old_name='certicate_number',
            new_name='certificate_no',
        ),
        migrations.RenameField(
            model_name='poj',
            old_name='total_val_j',
            new_name='total',
        ),
        migrations.RemoveField(
            model_name='inventoryofdiamond',
            name='depth',
        ),
        migrations.AddField(
            model_name='inventoryofdiamond',
            name='eepth',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventoryofdiamond',
            name='status',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='inventoryofdiamond',
            name='table',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='inventoryofdiamond',
            name='weight',
            field=models.FloatField(),
        ),
    ]
