# Generated by Django 3.2.5 on 2021-08-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0026_auto_20210807_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pod',
            name='total_val_d',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='total_value_d',
            name='total_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9),
        ),
    ]
