# Generated by Django 3.0.5 on 2022-01-06 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0027_auto_20220102_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorstone_media',
            name='stockid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='firstapp.Inventoryofcolorstones'),
        ),
    ]
