# Generated by Django 3.2.5 on 2021-08-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0029_alter_poj_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryofjewellery',
            name='purchaseapv',
            field=models.BooleanField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poj',
            name='purchase_approval',
            field=models.BooleanField(default=False),
        ),
    ]
