# Generated by Django 3.2.5 on 2021-08-08 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0030_auto_20210808_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryofjewellery',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
