# Generated by Django 3.0.5 on 2022-01-06 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0030_auto_20220106_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colorstone_media',
            name='id',
        ),
        migrations.RemoveField(
            model_name='diamond_media',
            name='id',
        ),
        migrations.RemoveField(
            model_name='jewel_media',
            name='id',
        ),
        migrations.AlterField(
            model_name='colorstone_media',
            name='stockid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='media', serialize=False, to='firstapp.Inventoryofcolorstones'),
        ),
        migrations.AlterField(
            model_name='diamond_media',
            name='Diamond_object',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='media', serialize=False, to='firstapp.Inventoryofdiamond'),
        ),
        migrations.AlterField(
            model_name='jewel_media',
            name='jewel_object',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='jewel_media', serialize=False, to='firstapp.Inventoryofjewellery'),
        ),
    ]
