# Generated by Django 3.2.5 on 2021-08-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0031_inventoryofjewellery_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='amount',
        ),
        migrations.DeleteModel(
            name='certificate_no',
        ),
        migrations.DeleteModel(
            name='certificate_no_d',
        ),
        migrations.DeleteModel(
            name='color_cs',
        ),
        migrations.DeleteModel(
            name='depths',
        ),
        migrations.DeleteModel(
            name='DIS',
        ),
        migrations.DeleteModel(
            name='DIS_amount',
        ),
        migrations.DeleteModel(
            name='fancy_colour_grade',
        ),
        migrations.DeleteModel(
            name='laser_inscription',
        ),
        migrations.DeleteModel(
            name='laser_inscription_d',
        ),
        migrations.DeleteModel(
            name='measurement_d',
        ),
        migrations.DeleteModel(
            name='measurements_cs',
        ),
        migrations.DeleteModel(
            name='measurements_d',
        ),
        migrations.DeleteModel(
            name='PCS_d',
        ),
        migrations.DeleteModel(
            name='price',
        ),
        migrations.DeleteModel(
            name='rate_d',
        ),
        migrations.DeleteModel(
            name='table',
        ),
        migrations.DeleteModel(
            name='tag_price_d',
        ),
        migrations.DeleteModel(
            name='total_value_d',
        ),
        migrations.DeleteModel(
            name='units',
        ),
        migrations.DeleteModel(
            name='weight_cs',
        ),
        migrations.DeleteModel(
            name='weight_d',
        ),
        migrations.RenameField(
            model_name='inventoryofdiamond',
            old_name='eepth',
            new_name='depth',
        ),
        migrations.RenameField(
            model_name='pod',
            old_name='certificate_no',
            new_name='certificate_no_d',
        ),
        migrations.AddField(
            model_name='inventoryofcolorstones',
            name='purchaseapproval_cs',
            field=models.BooleanField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventoryofdiamond',
            name='purchase_approval_d',
            field=models.BooleanField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pod',
            name='purchaseapvd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchaseofcolorstones',
            name='purchaseapvcs',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='inventoryofcolorstones',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='inventoryofdiamond',
            name='status',
            field=models.BooleanField(blank=True),
        ),
    ]
