# Generated by Django 3.2.5 on 2021-08-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0032_auto_20210808_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryofdiamond',
            name='stockid',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
