# Generated by Django 3.2.5 on 2021-08-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0033_inventoryofdiamond_stockid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryofdiamond',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
