# Generated by Django 3.2.5 on 2021-08-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0034_alter_inventoryofdiamond_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='cloneInvofjewellery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('stockid', models.CharField(max_length=30)),
                ('company_name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('jewellery_type', models.CharField(max_length=30)),
                ('center_stone', models.CharField(max_length=30)),
                ('shape', models.CharField(max_length=30)),
                ('metal', models.CharField(max_length=30)),
                ('gross_wt', models.FloatField()),
                ('certificate', models.CharField(max_length=30)),
                ('PCS', models.IntegerField()),
                ('amount', models.FloatField(blank=True)),
                ('DIS', models.FloatField(blank=True)),
                ('DIS_amount', models.FloatField(blank=True)),
                ('total_value', models.FloatField(blank=True)),
                ('currency', models.CharField(blank=True, max_length=30, null=True)),
                ('tag_price', models.FloatField()),
                ('rate', models.FloatField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Salesofjewellery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('stockid', models.CharField(max_length=30)),
                ('company_name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('jewellery_type', models.CharField(max_length=30)),
                ('center_stone', models.CharField(max_length=30)),
                ('shape', models.CharField(max_length=30)),
                ('metal', models.CharField(max_length=30)),
                ('gross_wt', models.FloatField()),
                ('certificate', models.CharField(max_length=30)),
                ('PCS', models.IntegerField()),
                ('amount', models.FloatField()),
                ('DIS', models.FloatField()),
                ('DIS_amount', models.FloatField()),
                ('total_value', models.FloatField()),
                ('currency', models.CharField(max_length=30)),
                ('tag_price', models.FloatField()),
                ('rate', models.FloatField()),
            ],
        ),
    ]
