# Generated by Django 3.2.5 on 2021-08-13 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0035_cloneinvofjewellery_salesofjewellery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloneinvofjewellery',
            name='date',
        ),
    ]
