# Generated by Django 3.2.5 on 2021-08-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0036_remove_cloneinvofjewellery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloneinvofjewellery',
            name='DIS',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cloneinvofjewellery',
            name='DIS_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cloneinvofjewellery',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cloneinvofjewellery',
            name='total_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
