# Generated by Django 3.2.5 on 2021-08-13 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0037_auto_20210813_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloneinvofjewellery',
            name='rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
