# Generated by Django 3.2.5 on 2021-08-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0038_alter_cloneinvofjewellery_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='poj',
            name='stockid',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
