# Generated by Django 3.2.5 on 2021-08-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0039_poj_stockid'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryofjewellery',
            name='cartstatus',
            field=models.BooleanField(default=False),
        ),
    ]
