# Generated by Django 3.2.5 on 2021-08-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0040_inventoryofjewellery_cartstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryofjewellery',
            name='appvreturnstatus',
            field=models.BooleanField(default=False),
        ),
    ]
