# Generated by Django 3.2.5 on 2021-08-23 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0041_inventoryofjewellery_appvreturnstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesofjewellery',
            name='center_stone',
        ),
    ]
