# Generated by Django 3.2.5 on 2021-08-28 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0043_salesofjewellery_center_stone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryofjewellery',
            name='status',
            field=models.CharField(default=False, max_length=30),
        ),
    ]
