# Generated by Django 3.2.5 on 2021-09-01 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0044_alter_inventoryofjewellery_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poj',
            name='stockid',
        ),
    ]
