# Generated by Django 3.2.5 on 2021-09-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0046_auto_20210906_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesofjewellery',
            name='DIS',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesofjewellery',
            name='DIS_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesofjewellery',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesofjewellery',
            name='currency',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='salesofjewellery',
            name='rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesofjewellery',
            name='total_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
