# Generated by Django 3.2.5 on 2021-09-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0047_auto_20210906_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloneinvofjewellery',
            name='salesapprovalstatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='salesofjewellery',
            name='salesapprovalstatus',
            field=models.BooleanField(default=False),
        ),
    ]
