# Generated by Django 3.2.5 on 2021-09-08 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0048_auto_20210906_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloneinvofjewellery',
            name='gross_wt',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='salesofjewellery',
            name='gross_wt',
            field=models.FloatField(null=True),
        ),
    ]
