# Generated by Django 3.2.5 on 2021-09-26 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0049_auto_20210908_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='cloneInvofcolorstones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockid', models.CharField(blank=True, max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('shape', models.CharField(max_length=30)),
                ('gem_type', models.CharField(max_length=30)),
                ('weight', models.IntegerField()),
                ('origin', models.CharField(max_length=30)),
                ('treatment', models.CharField(max_length=30)),
                ('certificate_no_cs', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('measurements', models.FloatField()),
                ('lab', models.CharField(max_length=30)),
                ('tag_price_cs', models.FloatField()),
                ('status', models.BooleanField(default=False)),
                ('amount_cs', models.FloatField(blank=True, null=True)),
                ('DIS_cs', models.FloatField(blank=True, null=True)),
                ('DIS_amount_cs', models.FloatField(blank=True, null=True)),
                ('total_value_cs', models.FloatField(blank=True, null=True)),
                ('currency_cs', models.CharField(blank=True, max_length=30, null=True)),
                ('rate_cs', models.FloatField(blank=True, null=True)),
                ('salesapprovalstatus_cs', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Salesofcolorstones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('stockid', models.CharField(max_length=30)),
                ('company_name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('shape', models.CharField(max_length=30)),
                ('gem_type', models.CharField(max_length=30)),
                ('origin', models.CharField(max_length=30)),
                ('treatment', models.CharField(max_length=30)),
                ('clarity', models.CharField(max_length=30)),
                ('certificate_no', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('measurements', models.FloatField()),
                ('lab', models.CharField(max_length=30)),
                ('PCS', models.IntegerField()),
                ('weight', models.FloatField()),
                ('price', models.FloatField()),
                ('units', models.IntegerField()),
                ('amount', models.FloatField(blank=True, null=True)),
                ('DIS', models.FloatField(blank=True, null=True)),
                ('DIS_amount', models.FloatField(blank=True, null=True)),
                ('total_value', models.FloatField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=30, null=True)),
                ('tag_price', models.FloatField()),
                ('rate', models.FloatField(blank=True, null=True)),
                ('salesapprovalstatus_cs', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='inventoryofcolorstones',
            name='appvreturnstatus_cs',
            field=models.BooleanField(default=False),
        ),
    ]
