# Generated by Django 3.2.5 on 2021-09-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0050_auto_20210926_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryofcolorstones',
            name='cartstatus',
            field=models.BooleanField(default=False),
        ),
    ]
