# Generated by Django 3.2.5 on 2021-09-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0054_cloneinvofcolorstones_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloneinvofcolorstones',
            name='Clarity',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventoryofcolorstones',
            name='Clarity',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
