# Generated by Django 3.2.5 on 2021-09-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0056_auto_20210928_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloneinvofcolorstones',
            name='status',
        ),
        migrations.AddField(
            model_name='cloneinvofcolorstones',
            name='price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cloneinvofcolorstones',
            name='units',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
