# Generated by Django 3.2.5 on 2021-09-28 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0057_auto_20210928_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesofcolorstones',
            old_name='DIS',
            new_name='DIS_amount_cs',
        ),
        migrations.RenameField(
            model_name='salesofcolorstones',
            old_name='DIS_amount',
            new_name='DIS_cs',
        ),
        migrations.RenameField(
            model_name='salesofcolorstones',
            old_name='amount',
            new_name='amount_cs',
        ),
        migrations.RenameField(
            model_name='salesofcolorstones',
            old_name='currency',
            new_name='currency_cs',
        ),
        migrations.RenameField(
            model_name='salesofcolorstones',
            old_name='rate',
            new_name='rate_cs',
        ),
        migrations.RenameField(
            model_name='salesofcolorstones',
            old_name='tag_price',
            new_name='tag_price_cs',
        ),
        migrations.RenameField(
            model_name='salesofcolorstones',
            old_name='total_value',
            new_name='total_value_cs',
        ),
    ]
