# Generated by Django 3.2.5 on 2021-09-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0058_auto_20210928_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesofcolorstones',
            name='Weight_cs',
            field=models.FloatField(null=True),
        ),
    ]
