# Generated by Django 3.2.5 on 2021-09-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0059_alter_salesofcolorstones_weight_cs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseofcolorstones',
            name='Weight_cs',
            field=models.FloatField(null=True),
        ),
    ]
