# Generated by Django 3.2.5 on 2021-09-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0061_auto_20210928_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloneinvofcolorstones',
            name='weight',
        ),
        migrations.AlterField(
            model_name='cloneinvofcolorstones',
            name='PCS',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cloneinvofcolorstones',
            name='Weight_cs',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cloneinvofcolorstones',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cloneinvofcolorstones',
            name='tag_price_cs',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cloneinvofcolorstones',
            name='units',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='inventoryofcolorstones',
            name='PCS',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='inventoryofcolorstones',
            name='measurements',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='inventoryofcolorstones',
            name='tag_price_cs',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='salesofcolorstones',
            name='PCS',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='salesofcolorstones',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='salesofcolorstones',
            name='tag_price_cs',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='salesofcolorstones',
            name='units',
            field=models.IntegerField(null=True),
        ),
    ]
