# Generated by Django 3.2.5 on 2021-09-28 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0062_auto_20210928_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloneinvofcolorstones',
            name='price',
        ),
        migrations.RemoveField(
            model_name='salesofcolorstones',
            name='price',
        ),
    ]
