# Generated by Django 3.2.5 on 2021-09-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0063_auto_20210928_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloneinvofcolorstones',
            name='units',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesofcolorstones',
            name='units',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
