# Generated by Django 3.2.5 on 2021-09-28 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0064_auto_20210928_2109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cloneinvofcolorstones',
            old_name='units',
            new_name='units_cs',
        ),
        migrations.RenameField(
            model_name='salesofcolorstones',
            old_name='units',
            new_name='units_cs',
        ),
    ]
