# Generated by Django 3.2.5 on 2021-09-29 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0066_auto_20210928_2122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesofdiamond',
            old_name='color_origin',
            new_name='color_origin1',
        ),
        migrations.RenameField(
            model_name='salesofdiamond',
            old_name='fancy_color_1',
            new_name='fancy_color_intensity1',
        ),
        migrations.RenameField(
            model_name='salesofdiamond',
            old_name='fancy_color_2',
            new_name='fancycolor_grade',
        ),
        migrations.RenameField(
            model_name='salesofdiamond',
            old_name='fancy_color_intensity',
            new_name='white_color_grade1',
        ),
        migrations.RemoveField(
            model_name='salesofdiamond',
            name='overtone',
        ),
        migrations.RemoveField(
            model_name='salesofdiamond',
            name='white_color_grade',
        ),
        migrations.AddField(
            model_name='cloneinvofdiamond',
            name='color_origin1',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
