# Generated by Django 3.2.5 on 2021-09-29 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0067_auto_20210929_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pod',
            name='price',
        ),
        migrations.RemoveField(
            model_name='salesofdiamond',
            name='price',
        ),
    ]
