# Generated by Django 3.2.5 on 2021-09-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0068_auto_20210929_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloneinvofdiamond',
            name='units',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
