# Generated by Django 3.2.5 on 2021-09-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0069_cloneinvofdiamond_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesofdiamond',
            name='DIS_Amount_d',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesofdiamond',
            name='DIS_d',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesofdiamond',
            name='amount_d',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesofdiamond',
            name='total_value_d',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
