# Generated by Django 3.2.5 on 2021-09-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0070_auto_20210929_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesofdiamond',
            name='currency',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='salesofdiamond',
            name='rate_d',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
