# Generated by Django 3.2.5 on 2021-09-29 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0071_auto_20210929_1900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryofcolorstones',
            old_name='purchaseapproval_cs',
            new_name='purchaseapv_cs',
        ),
    ]
