# Generated by Django 3.2.5 on 2021-10-05 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0072_rename_purchaseapproval_cs_inventoryofcolorstones_purchaseapv_cs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salesreturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('stockid', models.CharField(max_length=30)),
                ('company_name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('jewellery_type', models.CharField(max_length=30)),
            ],
        ),
    ]
