# Generated by Django 3.2.5 on 2021-10-05 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0074_salesreturn_cs_salesreturn_d'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesofcolorstones',
            old_name='certificate_no',
            new_name='certificate_no_cs',
        ),
    ]
