# Generated by Django 3.2.5 on 2021-10-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0075_rename_certificate_no_salesofcolorstones_certificate_no_cs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloneinvofcolorstones',
            name='measurements',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
