# Generated by Django 3.2.5 on 2021-10-05 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0077_alter_salesofcolorstones_measurements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloneinvofdiamond',
            name='measurements',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesofdiamond',
            name='measurements',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
