# Generated by Django 3.2.5 on 2021-10-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0078_auto_20211006_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryofdiamond',
            name='measurements',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
