# Generated by Django 3.2.5 on 2021-10-05 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0079_alter_inventoryofdiamond_measurements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryofdiamond',
            name='PCS_d',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryofdiamond',
            name='depth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryofdiamond',
            name='table',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryofdiamond',
            name='tag_price_d',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryofdiamond',
            name='weight_d',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
