# Generated by Django 3.2.5 on 2021-10-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0080_auto_20211006_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryofdiamond',
            name='units',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
