# Generated by Django 3.2.5 on 2021-10-06 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0083_auto_20211006_1914'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inventoryofcolorstones',
        ),
        migrations.DeleteModel(
            name='PurchaseOfColorStones',
        ),
    ]
