# Generated by Django 3.2.5 on 2021-10-06 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0084_auto_20211006_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventoryofcolorstones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockid', models.CharField(blank=True, max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('shape', models.CharField(max_length=30)),
                ('gem_type', models.CharField(max_length=30)),
                ('origin', models.CharField(max_length=30)),
                ('treatment', models.CharField(max_length=30)),
                ('Clarity', models.CharField(max_length=30)),
                ('certificate_no_cs', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('measurements', models.FloatField(null=True)),
                ('lab', models.CharField(max_length=30)),
                ('PCS', models.IntegerField(null=True)),
                ('Weight_cs', models.FloatField(null=True)),
                ('tag_price_cs', models.FloatField(null=True)),
                ('status', models.BooleanField(default=False)),
                ('purchaseapv_cs', models.BooleanField(blank=True)),
                ('appvreturnstatus_cs', models.BooleanField(default=False)),
                ('cartstatus', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOfColorStones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('stockid', models.CharField(blank=True, max_length=30)),
                ('Clarity', models.CharField(max_length=30)),
                ('colour', models.CharField(max_length=30)),
                ('measurements', models.IntegerField()),
                ('PCS', models.IntegerField()),
                ('Weight_cs', models.FloatField(null=True)),
                ('Price', models.FloatField()),
                ('units', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('discount', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('total_val_cs', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('purchaseapv_cs', models.BooleanField(default=False)),
                ('tag_price_cs', models.FloatField()),
                ('rate', models.FloatField()),
                ('Treatment', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.treatment_cs')),
                ('certificate_no_cs', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.certificate_no_cs')),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.companyinfo')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.currencies')),
                ('gem_type', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.gemtype')),
                ('lab', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.lab_cs')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.loc')),
                ('origin', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.origin_cs')),
                ('shape_cs', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.shape_cs')),
            ],
        ),
    ]
