# Generated by Django 3.2.5 on 2021-10-06 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0085_inventoryofcolorstones_purchaseofcolorstones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseofcolorstones',
            name='stockid',
        ),
    ]
