# Generated by Django 3.2.5 on 2021-10-07 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0086_remove_purchaseofcolorstones_stockid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryofcolorstones',
            old_name='Weight_cs',
            new_name='Weight',
        ),
        migrations.RenameField(
            model_name='inventoryofcolorstones',
            old_name='appvreturnstatus_cs',
            new_name='appvreturnstatus',
        ),
        migrations.RenameField(
            model_name='inventoryofcolorstones',
            old_name='purchaseapv_cs',
            new_name='purchaseapv',
        ),
        migrations.RenameField(
            model_name='inventoryofcolorstones',
            old_name='tag_price_cs',
            new_name='tag_price',
        ),
        migrations.RenameField(
            model_name='purchaseofcolorstones',
            old_name='Weight_cs',
            new_name='Weight',
        ),
    ]
