# Generated by Django 3.2.5 on 2021-10-07 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0088_auto_20211007_1210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cloneinvofcolorstones',
            old_name='certificate_no_cs',
            new_name='certificate_no',
        ),
        migrations.RenameField(
            model_name='salesofcolorstones',
            old_name='certificate_no_cs',
            new_name='certificate_no',
        ),
    ]
