# Generated by Django 3.2.5 on 2021-10-07 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0089_auto_20211007_1302'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='certificate_no_cs',
            new_name='cert_no_cs',
        ),
    ]
