# Generated by Django 3.2.5 on 2021-10-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0090_rename_certificate_no_cs_cert_no_cs'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesofdiamond',
            name='price',
            field=models.FloatField(default=32234.0),
            preserve_default=False,
        ),
    ]
