# Generated by Django 3.2.5 on 2021-10-07 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0092_alter_salesofdiamond_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currencies',
            name='country',
        ),
    ]
