# Generated by Django 3.2 on 2021-10-15 18:56

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0093_remove_currencies_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=30)),
                ('subject', tinymce.models.HTMLField(blank=True, null=True)),
            ],
        ),
    ]
