# Generated by Django 3.2 on 2021-10-17 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0095_blog_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryofjewellery',
            name='cert',
        ),
        migrations.RemoveField(
            model_name='poj',
            name='cert',
        ),
    ]
