# Generated by Django 3.2 on 2021-10-17 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0096_auto_20211017_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryofjewellery',
            name='cert',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poj',
            name='cert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.certificate'),
        ),
    ]
