# Generated by Django 3.2 on 2021-10-19 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0098_auto_20211019_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloneinvofjewellery',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.currencies'),
        ),
    ]
