# Generated by Django 3.2 on 2021-10-19 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0099_alter_cloneinvofjewellery_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='file',
            field=models.FileField(default=1, upload_to='certificate/'),
            preserve_default=False,
        ),
    ]
