# Generated by Django 3.2 on 2021-11-01 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0100_certificate_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jewel_media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='JewelleryMedia/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='JewelleryMedia/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='JewelleryMedia/')),
                ('video_embed_link', models.TextField(blank=True, null=True)),
                ('jewel_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.inventoryofjewellery')),
            ],
        ),
    ]
