# Generated by Django 3.2.5 on 2021-11-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0102_inventoryofjewellery_frontend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment_cs',
            name='treat',
            field=models.CharField(max_length=30),
        ),
    ]
