# Generated by Django 3.2.5 on 2021-11-12 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0104_auto_20211112_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloneinvofdiamond',
            name='measurements',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cloneinvofdiamond',
            name='units',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryofdiamond',
            name='measurements',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryofdiamond',
            name='units',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pod',
            name='measurements',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pod',
            name='units',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='salesofdiamond',
            name='measurements',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='salesofdiamond',
            name='units',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
