# Generated by Django 3.2.5 on 2021-11-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0107_purchaseofcolorstones_cert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseofcolorstones',
            name='date',
            field=models.DateField(),
        ),
    ]
