# Generated by Django 3.2.5 on 2021-11-12 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0108_alter_purchaseofcolorstones_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='loc',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='treatment_cs',
            old_name='treat',
            new_name='treatment',
        ),
    ]
