# Generated by Django 3.2.5 on 2021-11-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0109_auto_20211113_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreturn_cs',
            name='tag_price_cs',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='salesreturn_cs',
            name='weight',
            field=models.FloatField(null=True),
        ),
    ]
