# Generated by Django 3.2.5 on 2021-11-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0110_auto_20211113_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryofdiamond',
            name='purchaseapv_d',
            field=models.BooleanField(blank=True, verbose_name='Bought Diamond'),
        ),
    ]
