# Generated by Django 3.2.5 on 2021-11-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0111_alter_inventoryofdiamond_purchaseapv_d'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryofdiamond',
            name='purchaseapv_d',
            field=models.BooleanField(blank=True),
        ),
    ]
