# Generated by Django 3.2.5 on 2021-11-13 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0112_alter_inventoryofdiamond_purchaseapv_d'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloneinvofcolorstones',
            name='currency_cs',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='firstapp.currencies'),
            preserve_default=False,
        ),
    ]
