# Generated by Django 3.2.5 on 2021-11-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0114_alter_cloneinvofcolorstones_currency_cs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesofcolorstones',
            name='DIS_amount_cs',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesofcolorstones',
            name='DIS_cs',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesofcolorstones',
            name='amount_cs',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesofcolorstones',
            name='currency_cs',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesofcolorstones',
            name='rate_cs',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesofcolorstones',
            name='tag_price_cs',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesofcolorstones',
            name='total_value_cs',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
