# Generated by Django 3.2.5 on 2021-11-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0115_auto_20211113_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseofcolorstones',
            name='comment',
            field=models.TextField(blank=True, default='', max_length=3000, null=True),
        ),
    ]
