# Generated by Django 3.2.5 on 2021-11-14 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0118_alter_salesofcolorstones_pcs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesofjewellery',
            name='PCS',
            field=models.IntegerField(verbose_name='Pieces'),
        ),
    ]
