# Generated by Django 3.2.5 on 2021-11-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0119_alter_salesofjewellery_pcs'),
    ]

    operations = [
        migrations.AddField(
            model_name='pod',
            name='comment',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='poj',
            name='comment',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='salesofdiamond',
            name='comment',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='salesofjewellery',
            name='comment',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
    ]
