# Generated by Django 3.2.5 on 2021-11-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0120_auto_20211114_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesofcolorstones',
            name='Clarity',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Clarity'),
        ),
        migrations.AlterField(
            model_name='salesofcolorstones',
            name='DIS_amount_cs',
            field=models.FloatField(verbose_name='Discount Amount'),
        ),
        migrations.AlterField(
            model_name='salesofcolorstones',
            name='DIS_cs',
            field=models.FloatField(verbose_name='Discount Percentage'),
        ),
        migrations.AlterField(
            model_name='salesofcolorstones',
            name='Weight_cs',
            field=models.FloatField(null=True, verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='salesofcolorstones',
            name='amount_cs',
            field=models.FloatField(verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='salesofcolorstones',
            name='certificate_no',
            field=models.CharField(max_length=30, verbose_name='Certificate No.'),
        ),
        migrations.AlterField(
            model_name='salesofcolorstones',
            name='color',
            field=models.CharField(max_length=30, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='salesofcolorstones',
            name='comment',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='salesofcolorstones',
            name='company_name',
            field=models.CharField(max_length=30, verbose_name='Company name'),
        ),
        migrations.AlterField(
            model_name='salesofcolorstones',
            name='currency_cs',
            field=models.CharField(max_length=30, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='salesofcolorstones',
            name='date',
            field=models.DateField(verbose_name='Date of transaction'),
        ),
        migrations.AlterField(
            model_name='salesofcolorstones',
            name='gem_type',
            field=models.CharField(max_length=30, verbose_name='Gem Type'),
        ),
        migrations.AlterField(
            model_name='salesofcolorstones',
            name='lab',
            field=models.CharField(max_length=30, verbose_name='Lab'),
        ),
        migrations.AlterField(
            model_name='salesofcolorstones',
            name='location',
            field=models.CharField(max_length=30, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='salesofcolorstones',
            name='measurements',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Measurement'),
        ),
        migrations.AlterField(
            model_name='salesofcolorstones',
            name='origin',
            field=models.CharField(max_length=30, verbose_name='Origin'),
        ),
        migrations.AlterField(
            model_name='salesofcolorstones',
            name='rate_cs',
            field=models.FloatField(verbose_name='Rate'),
        ),
        migrations.AlterField(
            model_name='salesofcolorstones',
            name='salesapprovalstatus_cs',
            field=models.BooleanField(default=False, verbose_name='Sold'),
        ),
        migrations.AlterField(
            model_name='salesofcolorstones',
            name='shape',
            field=models.CharField(max_length=30, verbose_name='Shape'),
        ),
        migrations.AlterField(
            model_name='salesofcolorstones',
            name='stockid',
            field=models.CharField(max_length=30, verbose_name='Stock ID'),
        ),
        migrations.AlterField(
            model_name='salesofcolorstones',
            name='tag_price_cs',
            field=models.FloatField(verbose_name='Tag Price'),
        ),
        migrations.AlterField(
            model_name='salesofcolorstones',
            name='total_value_cs',
            field=models.FloatField(verbose_name='Total Value'),
        ),
        migrations.AlterField(
            model_name='salesofcolorstones',
            name='treatment',
            field=models.CharField(max_length=30, verbose_name='Treatment'),
        ),
    ]
