# Generated by Django 3.2.5 on 2021-11-14 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0121_auto_20211114_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='jewel_media',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='Certificates/Jewellery/'),
        ),
        migrations.AddField(
            model_name='jewel_media',
            name='image10',
            field=models.ImageField(blank=True, null=True, upload_to='JewelleryMedia/'),
        ),
        migrations.AddField(
            model_name='jewel_media',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='JewelleryMedia/'),
        ),
        migrations.AddField(
            model_name='jewel_media',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='JewelleryMedia/'),
        ),
        migrations.AddField(
            model_name='jewel_media',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='JewelleryMedia/'),
        ),
        migrations.AddField(
            model_name='jewel_media',
            name='image7',
            field=models.ImageField(blank=True, null=True, upload_to='JewelleryMedia/'),
        ),
        migrations.AddField(
            model_name='jewel_media',
            name='image8',
            field=models.ImageField(blank=True, null=True, upload_to='JewelleryMedia/'),
        ),
        migrations.AddField(
            model_name='jewel_media',
            name='image9',
            field=models.ImageField(blank=True, null=True, upload_to='JewelleryMedia/'),
        ),
        migrations.CreateModel(
            name='ColorStone_media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='ColorStoneMedia/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='ColorStoneMedia/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='ColorStoneMedia/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='ColorStoneMedia/')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='ColorStoneMedia/')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='ColorStoneMedia/')),
                ('image7', models.ImageField(blank=True, null=True, upload_to='ColorStoneMedia/')),
                ('image8', models.ImageField(blank=True, null=True, upload_to='ColorStoneMedia/')),
                ('image9', models.ImageField(blank=True, null=True, upload_to='ColorStoneMedia/')),
                ('image10', models.ImageField(blank=True, null=True, upload_to='ColorStoneMedia/')),
                ('video_embed_link', models.TextField(blank=True, null=True)),
                ('certificate', models.FileField(blank=True, null=True, upload_to='Certificates/ColorStone/')),
                ('jewel_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.inventoryofcolorstones')),
            ],
            options={
                'verbose_name_plural': 'ColorStone Media',
            },
        ),
    ]
