# Generated by Django 3.2.5 on 2021-11-14 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0122_auto_20211114_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='file',
        ),
    ]
