# Generated by Django 3.2.5 on 2021-11-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0123_remove_certificate_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'verbose_name_plural': 'ColorStone Certificates Types'},
        ),
        migrations.AddField(
            model_name='cloneinvofcolorstones',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cloneinvofcolorstones',
            name='units_cs',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='salesofcolorstones',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='salesofcolorstones',
            name='units_cs',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='salesofcolorstones',
            name='PCS',
            field=models.IntegerField(default=1, verbose_name='Pieces'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesofcolorstones',
            name='Weight_cs',
            field=models.FloatField(default=1, verbose_name='Weight'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesofcolorstones',
            name='rate_cs',
            field=models.FloatField(default=1, verbose_name='Rate'),
        ),
    ]
