# Generated by Django 3.2.5 on 2021-11-14 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0125_cloneinvofcolorstones_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloneinvofcolorstones',
            name='DIS_amount_cs',
            field=models.FloatField(blank=True, null=True, verbose_name='Discounted Amount'),
        ),
        migrations.AlterField(
            model_name='cloneinvofcolorstones',
            name='DIS_cs',
            field=models.FloatField(blank=True, null=True, verbose_name='Discount in %'),
        ),
        migrations.AlterField(
            model_name='cloneinvofcolorstones',
            name='PCS',
            field=models.IntegerField(null=True, verbose_name='Pieces'),
        ),
        migrations.AlterField(
            model_name='cloneinvofcolorstones',
            name='Weight_cs',
            field=models.FloatField(null=True, verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='cloneinvofcolorstones',
            name='amount_cs',
            field=models.FloatField(blank=True, null=True, verbose_name='Amount Per CTS'),
        ),
        migrations.AlterField(
            model_name='cloneinvofcolorstones',
            name='company_name',
            field=models.CharField(max_length=30, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='cloneinvofcolorstones',
            name='currency_cs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.currencies', verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='cloneinvofcolorstones',
            name='location',
            field=models.CharField(max_length=30, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='cloneinvofcolorstones',
            name='rate_cs',
            field=models.FloatField(blank=True, default=1, null=True, verbose_name='Rate'),
        ),
        migrations.AlterField(
            model_name='cloneinvofcolorstones',
            name='shape',
            field=models.CharField(max_length=30, verbose_name='Shape'),
        ),
        migrations.AlterField(
            model_name='cloneinvofcolorstones',
            name='stockid',
            field=models.CharField(blank=True, max_length=30, verbose_name='Stock ID'),
        ),
        migrations.AlterField(
            model_name='cloneinvofcolorstones',
            name='tag_price_cs',
            field=models.FloatField(null=True, verbose_name='Tag Price'),
        ),
        migrations.AlterField(
            model_name='cloneinvofcolorstones',
            name='total_value_cs',
            field=models.FloatField(blank=True, null=True, verbose_name='Total Value'),
        ),
        migrations.AlterField(
            model_name='cloneinvofcolorstones',
            name='units_cs',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Units'),
        ),
    ]
