# Generated by Django 3.2.5 on 2021-11-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0126_auto_20211114_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryofcolorstones',
            name='frontend',
            field=models.BooleanField(default=False),
        ),
    ]
