# Generated by Django 3.2.5 on 2021-11-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0128_alter_purchaseofcolorstones_certificate_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colorstone_media',
            old_name='jewel_object',
            new_name='stockid',
        ),
        migrations.RemoveField(
            model_name='purchaseofcolorstones',
            name='cert',
        ),
        migrations.AlterField(
            model_name='purchaseofcolorstones',
            name='certificate_no',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Certificate Number'),
        ),
    ]
