# Generated by Django 3.2.5 on 2021-11-18 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0129_auto_20211117_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloneinvofcolorstones',
            name='company_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.companyinfo', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='GST_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='line_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='pan_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='website',
            field=models.EmailField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='wechat_id',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
