# Generated by Django 3.2.5 on 2021-11-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0130_auto_20211118_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesofcolorstones',
            name='DIS_amount_cs',
            field=models.FloatField(blank=True, null=True, verbose_name='Discount Amount'),
        ),
        migrations.AlterField(
            model_name='salesofcolorstones',
            name='DIS_cs',
            field=models.FloatField(blank=True, null=True, verbose_name='Discount Percentage'),
        ),
        migrations.AlterField(
            model_name='salesofcolorstones',
            name='amount_cs',
            field=models.FloatField(blank=True, null=True, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='salesofcolorstones',
            name='total_value_cs',
            field=models.FloatField(blank=True, null=True, verbose_name='Total Value'),
        ),
    ]
