# Generated by Django 3.2.5 on 2021-11-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0131_auto_20211118_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloneinvofcolorstones',
            name='DIS_amount_cs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Discounted Amount'),
        ),
        migrations.AlterField(
            model_name='cloneinvofcolorstones',
            name='DIS_cs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Discount in %'),
        ),
        migrations.AlterField(
            model_name='cloneinvofcolorstones',
            name='amount_cs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Amount Per CTS'),
        ),
        migrations.AlterField(
            model_name='cloneinvofcolorstones',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='cloneinvofcolorstones',
            name='rate_cs',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=9, null=True, verbose_name='Rate'),
        ),
        migrations.AlterField(
            model_name='cloneinvofcolorstones',
            name='tag_price_cs',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True, verbose_name='Tag Price'),
        ),
        migrations.AlterField(
            model_name='cloneinvofcolorstones',
            name='total_value_cs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Total Value'),
        ),
        migrations.AlterField(
            model_name='salesofcolorstones',
            name='DIS_amount_cs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Discount Amount'),
        ),
        migrations.AlterField(
            model_name='salesofcolorstones',
            name='DIS_cs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Discount Percentage'),
        ),
        migrations.AlterField(
            model_name='salesofcolorstones',
            name='Weight_cs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='salesofcolorstones',
            name='amount_cs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='salesofcolorstones',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='salesofcolorstones',
            name='rate_cs',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9, verbose_name='Rate'),
        ),
        migrations.AlterField(
            model_name='salesofcolorstones',
            name='tag_price_cs',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Tag Price'),
        ),
        migrations.AlterField(
            model_name='salesofcolorstones',
            name='total_value_cs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Total Value'),
        ),
    ]
