# Generated by Django 3.2.5 on 2021-11-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0132_auto_20211119_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryofcolorstones',
            name='Weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Weight'),
        ),
    ]
