# Generated by Django 3.2.5 on 2021-11-19 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0133_alter_inventoryofcolorstones_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesofcolorstones',
            name='currency_cs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.currencies', verbose_name='Currency'),
        ),
    ]
