# Generated by Django 3.2.5 on 2021-11-19 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0134_alter_salesofcolorstones_currency_cs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloneinvofcolorstones',
            name='gem_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.gemtype'),
        ),
        migrations.AlterField(
            model_name='cloneinvofcolorstones',
            name='lab',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.lab_cs'),
        ),
        migrations.AlterField(
            model_name='cloneinvofcolorstones',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.location'),
        ),
        migrations.AlterField(
            model_name='cloneinvofcolorstones',
            name='origin',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.origin_cs'),
        ),
        migrations.AlterField(
            model_name='cloneinvofcolorstones',
            name='shape',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.shape_cs'),
        ),
        migrations.AlterField(
            model_name='cloneinvofcolorstones',
            name='stockid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.purchaseofcolorstones'),
        ),
        migrations.AlterField(
            model_name='cloneinvofcolorstones',
            name='treatment',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.treatment_cs'),
        ),
        migrations.AlterField(
            model_name='inventoryofcolorstones',
            name='gem_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.gemtype'),
        ),
        migrations.AlterField(
            model_name='inventoryofcolorstones',
            name='lab',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.lab_cs'),
        ),
        migrations.AlterField(
            model_name='inventoryofcolorstones',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.location'),
        ),
        migrations.AlterField(
            model_name='inventoryofcolorstones',
            name='origin',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.origin_cs'),
        ),
        migrations.AlterField(
            model_name='inventoryofcolorstones',
            name='shape',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.shape_cs'),
        ),
        migrations.AlterField(
            model_name='inventoryofcolorstones',
            name='stockid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.purchaseofcolorstones'),
        ),
        migrations.AlterField(
            model_name='inventoryofcolorstones',
            name='treatment',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.treatment_cs'),
        ),
        migrations.AlterField(
            model_name='salesofcolorstones',
            name='company_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.companyinfo'),
        ),
        migrations.AlterField(
            model_name='salesofcolorstones',
            name='gem_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.gemtype'),
        ),
        migrations.AlterField(
            model_name='salesofcolorstones',
            name='lab',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.lab_cs'),
        ),
        migrations.AlterField(
            model_name='salesofcolorstones',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.location'),
        ),
        migrations.AlterField(
            model_name='salesofcolorstones',
            name='origin',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.origin_cs'),
        ),
        migrations.AlterField(
            model_name='salesofcolorstones',
            name='shape',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.shape_cs'),
        ),
        migrations.AlterField(
            model_name='salesofcolorstones',
            name='stockid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.purchaseofcolorstones'),
        ),
        migrations.AlterField(
            model_name='salesofcolorstones',
            name='treatment',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.treatment_cs'),
        ),
        migrations.AlterField(
            model_name='salesreturn_cs',
            name='gem_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.gemtype'),
        ),
        migrations.AlterField(
            model_name='salesreturn_cs',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.location'),
        ),
    ]
