# Generated by Django 3.2.5 on 2021-11-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0135_auto_20211119_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloneinvofcolorstones',
            name='stockid',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='inventoryofcolorstones',
            name='stockid',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='salesofcolorstones',
            name='stockid',
            field=models.CharField(max_length=30),
        ),
    ]
