# Generated by Django 3.2.5 on 2021-11-19 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0136_auto_20211119_1937'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cert_no_cs',
        ),
        migrations.AlterModelOptions(
            name='color_origin',
            options={'verbose_name_plural': 'ColorStone - Origin'},
        ),
        migrations.AlterModelOptions(
            name='colorstone_media',
            options={'verbose_name_plural': 'ColorStone - Media'},
        ),
        migrations.AlterModelOptions(
            name='companyinfo',
            options={'verbose_name_plural': 'Company Details'},
        ),
        migrations.AlterModelOptions(
            name='currencies',
            options={'verbose_name_plural': 'Currencies'},
        ),
        migrations.AlterModelOptions(
            name='gemtype',
            options={'verbose_name_plural': 'ColorStone - Gem'},
        ),
        migrations.AlterModelOptions(
            name='lab_cs',
            options={'verbose_name_plural': 'ColorStone - Labs'},
        ),
        migrations.AlterModelOptions(
            name='origin_cs',
            options={'verbose_name_plural': 'ColorStone - Origin'},
        ),
        migrations.AlterModelOptions(
            name='salesofcolorstones',
            options={'verbose_name_plural': 'ColorStone - Sales'},
        ),
        migrations.AlterModelOptions(
            name='shape_cs',
            options={'verbose_name_plural': 'ColorStone - Shape'},
        ),
        migrations.AlterModelOptions(
            name='treatment_cs',
            options={'verbose_name_plural': 'ColorStone - Treatment'},
        ),
    ]
