# Generated by Django 3.2.5 on 2021-11-19 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0137_auto_20211119_2025'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Database',
        ),
    ]
