# Generated by Django 3.2.5 on 2021-11-19 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0138_delete_database'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'verbose_name_plural': 'ColourStone Certificates Types'},
        ),
        migrations.AlterModelOptions(
            name='color_origin',
            options={'verbose_name_plural': 'ColourStone - Origin'},
        ),
        migrations.AlterModelOptions(
            name='colorstone_media',
            options={'verbose_name_plural': 'ColourStone - Media'},
        ),
        migrations.AlterModelOptions(
            name='countries',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='gemtype',
            options={'verbose_name_plural': 'ColourStone - Gem'},
        ),
        migrations.AlterModelOptions(
            name='lab_cs',
            options={'verbose_name_plural': 'ColourStone - Labs'},
        ),
        migrations.AlterModelOptions(
            name='origin_cs',
            options={'verbose_name_plural': 'ColourStone - Origin'},
        ),
        migrations.AlterModelOptions(
            name='salesofcolorstones',
            options={'verbose_name_plural': 'ColourStone - Sales'},
        ),
        migrations.AlterModelOptions(
            name='shape_cs',
            options={'verbose_name_plural': 'ColourStone - Shape'},
        ),
        migrations.AlterModelOptions(
            name='treatment_cs',
            options={'verbose_name_plural': 'ColourStone - Treatment'},
        ),
    ]
