# Generated by Django 3.2.5 on 2021-11-20 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0141_user_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_table',
            name='email_id',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
