# Generated by Django 3.2.5 on 2021-11-20 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0142_alter_user_table_email_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_table',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.RemoveField(
            model_name='user_table',
            name='id',
        ),
        migrations.AlterField(
            model_name='user_table',
            name='email_id',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True),
        ),
    ]
