# Generated by Django 3.2.5 on 2021-11-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0143_auto_20211120_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_table',
            name='permit_user',
            field=models.BooleanField(default=False),
        ),
    ]
