# Generated by Django 3.2.5 on 2021-11-22 19:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0145_auto_20211120_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryofjewellery',
            name='status',
        ),
        migrations.RemoveField(
            model_name='poj',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='cloneinvofjewellery',
            name='center_stone_pieces',
            field=models.BigIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cloneinvofjewellery',
            name='center_stone_weight',
            field=models.DecimalField(decimal_places=2, default=2.33, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cloneinvofjewellery',
            name='color_of_center_stone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.colorofcstone'),
        ),
        migrations.AddField(
            model_name='cloneinvofjewellery',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventoryofjewellery',
            name='center_stone_pieces',
            field=models.BigIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventoryofjewellery',
            name='center_stone_weight',
            field=models.DecimalField(decimal_places=2, default=2.33, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poj',
            name='center_stone_pieces',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poj',
            name='center_stone_weight',
            field=models.DecimalField(decimal_places=2, default=2.33, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesofjewellery',
            name='center_stone_pieces',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesofjewellery',
            name='center_stone_weight',
            field=models.DecimalField(decimal_places=2, default=2.22, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesofjewellery',
            name='color_of_center_stone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.colorofcstone'),
        ),
        migrations.AlterField(
            model_name='cloneinvofjewellery',
            name='DIS',
            field=models.DecimalField(blank=True, decimal_places=2, default=2.0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cloneinvofjewellery',
            name='DIS_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=3.44, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cloneinvofjewellery',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=3.44, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cloneinvofjewellery',
            name='center_stone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.centerstone'),
        ),
        migrations.AlterField(
            model_name='cloneinvofjewellery',
            name='certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.certificate'),
        ),
        migrations.AlterField(
            model_name='cloneinvofjewellery',
            name='company_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.companyinfo', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='cloneinvofjewellery',
            name='gross_wt',
            field=models.DecimalField(blank=True, decimal_places=2, default=3.44, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cloneinvofjewellery',
            name='jewellery_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.jewell'),
        ),
        migrations.AlterField(
            model_name='cloneinvofjewellery',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.location'),
        ),
        migrations.AlterField(
            model_name='cloneinvofjewellery',
            name='metal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.metal1'),
        ),
        migrations.AlterField(
            model_name='cloneinvofjewellery',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cloneinvofjewellery',
            name='shape',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.shape1'),
        ),
        migrations.AlterField(
            model_name='cloneinvofjewellery',
            name='tag_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='cloneinvofjewellery',
            name='total_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventoryofjewellery',
            name='center_stone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.centerstone'),
        ),
        migrations.AlterField(
            model_name='inventoryofjewellery',
            name='cert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.certificate'),
        ),
        migrations.AlterField(
            model_name='inventoryofjewellery',
            name='color_of_center_stone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.colorofcstone'),
        ),
        migrations.AlterField(
            model_name='inventoryofjewellery',
            name='grosswt',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='inventoryofjewellery',
            name='jewellery_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.jewell'),
        ),
        migrations.AlterField(
            model_name='inventoryofjewellery',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.location'),
        ),
        migrations.AlterField(
            model_name='inventoryofjewellery',
            name='metal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.metal1'),
        ),
        migrations.AlterField(
            model_name='inventoryofjewellery',
            name='shape',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.shape1'),
        ),
        migrations.AlterField(
            model_name='inventoryofjewellery',
            name='tag_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='poj',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='poj',
            name='grosswt',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='poj',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='poj',
            name='tag_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='salesofjewellery',
            name='DIS',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='salesofjewellery',
            name='DIS_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='salesofjewellery',
            name='PCS',
            field=models.BigIntegerField(verbose_name='Pieces'),
        ),
        migrations.AlterField(
            model_name='salesofjewellery',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='salesofjewellery',
            name='center_stone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.centerstone'),
        ),
        migrations.AlterField(
            model_name='salesofjewellery',
            name='certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.certificate'),
        ),
        migrations.AlterField(
            model_name='salesofjewellery',
            name='company_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.companyinfo'),
        ),
        migrations.AlterField(
            model_name='salesofjewellery',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.currencies', verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='salesofjewellery',
            name='date',
            field=models.DateField(verbose_name='Date of transaction'),
        ),
        migrations.AlterField(
            model_name='salesofjewellery',
            name='gross_wt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='salesofjewellery',
            name='jewellery_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.jewell'),
        ),
        migrations.AlterField(
            model_name='salesofjewellery',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.location'),
        ),
        migrations.AlterField(
            model_name='salesofjewellery',
            name='metal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.metal1'),
        ),
        migrations.AlterField(
            model_name='salesofjewellery',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='salesofjewellery',
            name='shape',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.shape1'),
        ),
        migrations.AlterField(
            model_name='salesofjewellery',
            name='tag_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='salesofjewellery',
            name='total_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9),
        ),
    ]
