# Generated by Django 3.2.5 on 2021-11-22 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0146_auto_20211123_0052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poj',
            old_name='currencyid',
            new_name='currency',
        ),
    ]
