# Generated by Django 3.2.5 on 2021-11-22 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0147_rename_currencyid_poj_currency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='centerstone',
            options={'verbose_name_plural': 'Jewellery - Center Stone'},
        ),
        migrations.AlterModelOptions(
            name='certificate',
            options={'verbose_name_plural': 'Jewellery Certificates Types'},
        ),
        migrations.AlterModelOptions(
            name='colorofcstone',
            options={'verbose_name_plural': 'Jewellery - Colour of Center Stone'},
        ),
        migrations.AlterModelOptions(
            name='jewell',
            options={'verbose_name_plural': 'Jewellery -Type'},
        ),
        migrations.AlterModelOptions(
            name='metal1',
            options={'verbose_name_plural': 'Jewellery - Metal'},
        ),
        migrations.AlterModelOptions(
            name='shape1',
            options={'verbose_name_plural': 'Jewellery - Shape'},
        ),
        migrations.AlterField(
            model_name='cloneinvofjewellery',
            name='DIS',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='cloneinvofjewellery',
            name='DIS_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='cloneinvofjewellery',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='cloneinvofjewellery',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=9),
        ),
        migrations.AlterField(
            model_name='cloneinvofjewellery',
            name='total_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
