# Generated by Django 3.2.5 on 2021-11-23 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0148_auto_20211123_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorstone_media',
            name='colorstone_info',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Colour Stone Information'),
        ),
        migrations.AddField(
            model_name='colorstone_media',
            name='description',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='jewel_media',
            name='description',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='jewel_media',
            name='jewellery_info',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Jewellery Information'),
        ),
    ]
