# Generated by Django 3.2.5 on 2021-11-23 08:50

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0149_auto_20211123_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorstone_media',
            name='colorstone_info',
            field=tinymce.models.HTMLField(blank=True, max_length=3000, null=True, verbose_name='Colour Stone Information'),
        ),
        migrations.AlterField(
            model_name='jewel_media',
            name='jewellery_info',
            field=tinymce.models.HTMLField(blank=True, max_length=3000, null=True, verbose_name='Jewellery Information'),
        ),
    ]
