# Generated by Django 3.2.5 on 2021-11-23 08:55

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0151_auto_20211123_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorstone_media',
            name='colorstone_info',
            field=tinymce.models.HTMLField(blank=True, max_length=3000, null=True, verbose_name='Colour Stone Information'),
        ),
        migrations.AddField(
            model_name='colorstone_media',
            name='description',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Description'),
        ),
    ]
