# Generated by Django 3.2.9 on 2021-11-29 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0153_auto_20211123_1427'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'verbose_name_plural': 'Jewellery - Certificates Types'},
        ),
        migrations.AlterModelOptions(
            name='jewel_media',
            options={'verbose_name_plural': 'Jewellery - Media'},
        ),
        migrations.AlterModelOptions(
            name='salesofjewellery',
            options={'verbose_name_plural': 'Jewellery - Sales'},
        ),
    ]
