# Generated by Django 3.2.9 on 2021-11-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0154_auto_20211129_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pod',
            name='date',
            field=models.DateField(),
        ),
    ]
