# Generated by Django 3.2.9 on 2021-11-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0155_alter_pod_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pod',
            name='fancycolor_grade',
            field=models.CharField(max_length=100),
        ),
    ]
