# Generated by Django 3.2.9 on 2021-11-29 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0156_alter_pod_fancycolor_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryofdiamond',
            name='fancy_color_intensity1',
        ),
        migrations.RemoveField(
            model_name='inventoryofdiamond',
            name='price',
        ),
        migrations.RemoveField(
            model_name='inventoryofdiamond',
            name='status',
        ),
        migrations.RemoveField(
            model_name='pod',
            name='fancy_color_intensity1',
        ),
        migrations.AlterField(
            model_name='inventoryofdiamond',
            name='certificate_d',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.certificate_d'),
        ),
        migrations.AlterField(
            model_name='inventoryofdiamond',
            name='cut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.cut'),
        ),
        migrations.AlterField(
            model_name='inventoryofdiamond',
            name='depth',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventoryofdiamond',
            name='fancycolor_grade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryofdiamond',
            name='fluorescence_color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.fluorescence_color'),
        ),
        migrations.AlterField(
            model_name='inventoryofdiamond',
            name='fluorescence_intensity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.fluorescence_intensity'),
        ),
        migrations.AlterField(
            model_name='inventoryofdiamond',
            name='laser_inscription',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='inventoryofdiamond',
            name='polish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.polish'),
        ),
        migrations.AlterField(
            model_name='inventoryofdiamond',
            name='symmetry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.symmetry'),
        ),
        migrations.AlterField(
            model_name='inventoryofdiamond',
            name='table',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='inventoryofdiamond',
            name='weight_d',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='inventoryofdiamond',
            name='white_color_grade1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.white_color_grade'),
        ),
        migrations.AlterField(
            model_name='pod',
            name='DIS_d',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='pod',
            name='fancycolor_grade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pod',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='pod',
            name='weight_d',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='pod',
            name='white_color_grade1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.white_color_grade'),
        ),
    ]
