# Generated by Django 3.2.9 on 2021-11-30 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0158_inventoryofdiamond_color_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloneinvofdiamond',
            name='fancy_color_intensity1',
        ),
        migrations.RemoveField(
            model_name='salesofdiamond',
            name='fancy_color_intensity1',
        ),
        migrations.AlterField(
            model_name='inventoryofdiamond',
            name='clarity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.clarity'),
        ),
        migrations.AlterField(
            model_name='inventoryofdiamond',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.location'),
        ),
        migrations.AlterField(
            model_name='inventoryofdiamond',
            name='shape',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.shape_d'),
        ),
    ]
