# Generated by Django 3.2.9 on 2021-11-30 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0159_auto_20211130_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryofdiamond',
            name='color_grade',
        ),
        migrations.RemoveField(
            model_name='salesofdiamond',
            name='fancy_color_grade',
        ),
        migrations.AddField(
            model_name='inventoryofdiamond',
            name='color_origin1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='firstapp.color_origin'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventoryofdiamond',
            name='tag_price_d',
            field=models.DecimalField(decimal_places=2, default=123.22, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pod',
            name='depth',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='pod',
            name='rate_d',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='pod',
            name='table_perc',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='pod',
            name='tag_price_d',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='salesofdiamond',
            name='certificate_d',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.certificate_d'),
        ),
        migrations.AlterField(
            model_name='salesofdiamond',
            name='clarity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.clarity'),
        ),
        migrations.AlterField(
            model_name='salesofdiamond',
            name='company_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.companyinfo'),
        ),
        migrations.AlterField(
            model_name='salesofdiamond',
            name='cut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.cut'),
        ),
        migrations.AlterField(
            model_name='salesofdiamond',
            name='depth',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesofdiamond',
            name='fluorescence_color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.fluorescence_color'),
        ),
        migrations.AlterField(
            model_name='salesofdiamond',
            name='fluorescence_intensity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.fluorescence_intensity'),
        ),
        migrations.AlterField(
            model_name='salesofdiamond',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.location'),
        ),
        migrations.AlterField(
            model_name='salesofdiamond',
            name='polish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.polish'),
        ),
        migrations.AlterField(
            model_name='salesofdiamond',
            name='shape',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.shape_d'),
        ),
        migrations.AlterField(
            model_name='salesofdiamond',
            name='symmetry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.symmetry'),
        ),
        migrations.AlterField(
            model_name='salesofdiamond',
            name='table',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesofdiamond',
            name='white_color_grade1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.white_color_grade'),
        ),
    ]
