# Generated by Django 3.2.9 on 2021-11-30 18:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0160_auto_20211130_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloneinvofdiamond',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cloneinvofdiamond',
            name='DIS_Amount_d',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cloneinvofdiamond',
            name='DIS_d',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cloneinvofdiamond',
            name='amount_d',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cloneinvofdiamond',
            name='clarity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.clarity'),
        ),
        migrations.AlterField(
            model_name='cloneinvofdiamond',
            name='color_origin1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.color_origin'),
        ),
        migrations.AlterField(
            model_name='cloneinvofdiamond',
            name='company_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.companyinfo'),
        ),
        migrations.AlterField(
            model_name='cloneinvofdiamond',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='firstapp.currencies'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cloneinvofdiamond',
            name='cut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.cut'),
        ),
        migrations.AlterField(
            model_name='cloneinvofdiamond',
            name='depth',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cloneinvofdiamond',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.location'),
        ),
        migrations.AlterField(
            model_name='cloneinvofdiamond',
            name='polish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.polish'),
        ),
        migrations.AlterField(
            model_name='cloneinvofdiamond',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cloneinvofdiamond',
            name='rate_d',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cloneinvofdiamond',
            name='shape',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.shape_d'),
        ),
        migrations.AlterField(
            model_name='cloneinvofdiamond',
            name='symmetry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.symmetry'),
        ),
        migrations.AlterField(
            model_name='cloneinvofdiamond',
            name='table',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cloneinvofdiamond',
            name='tag_price_d',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='cloneinvofdiamond',
            name='total_value_d',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cloneinvofdiamond',
            name='weight_d',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cloneinvofdiamond',
            name='white_color_grade1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.white_color_grade'),
        ),
        migrations.AlterField(
            model_name='salesofdiamond',
            name='DIS_Amount_d',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesofdiamond',
            name='DIS_d',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesofdiamond',
            name='amount_d',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesofdiamond',
            name='color_origin1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.color_origin'),
        ),
        migrations.AlterField(
            model_name='salesofdiamond',
            name='currency',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesofdiamond',
            name='date',
            field=models.DateField(verbose_name='Date of transaction'),
        ),
        migrations.AlterField(
            model_name='salesofdiamond',
            name='laser_inscription',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='salesofdiamond',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesofdiamond',
            name='rate_d',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesofdiamond',
            name='tag_price_d',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='salesofdiamond',
            name='total_value_d',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesofdiamond',
            name='units',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesofdiamond',
            name='weight_d',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9),
            preserve_default=False,
        ),
    ]
