# Generated by Django 3.2.9 on 2021-11-30 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0161_auto_20211201_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesofdiamond',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.currencies'),
        ),
    ]
