# Generated by Django 3.2.9 on 2021-11-30 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0163_alter_cloneinvofdiamond_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloneinvofdiamond',
            name='certificate_d',
        ),
        migrations.AlterField(
            model_name='cloneinvofdiamond',
            name='DIS_Amount_d',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=9, null=True, verbose_name='Discount Amount'),
        ),
        migrations.AlterField(
            model_name='cloneinvofdiamond',
            name='DIS_d',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=9, null=True, verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='cloneinvofdiamond',
            name='amount_d',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=9, null=True, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='cloneinvofdiamond',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=9, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='cloneinvofdiamond',
            name='rate_d',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=9, null=True, verbose_name='Rate'),
        ),
        migrations.AlterField(
            model_name='cloneinvofdiamond',
            name='tag_price_d',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=9, null=True, verbose_name='Tag Price'),
        ),
        migrations.AlterField(
            model_name='cloneinvofdiamond',
            name='total_value_d',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=9, null=True, verbose_name='Total Value'),
        ),
    ]
