# Generated by Django 3.2.9 on 2021-11-30 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0164_auto_20211201_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloneinvofdiamond',
            name='certificate_d',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='firstapp.certificate_d'),
            preserve_default=False,
        ),
    ]
