# Generated by Django 3.2.9 on 2021-11-30 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0165_cloneinvofdiamond_certificate_d'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloneinvofdiamond',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.currencies'),
        ),
    ]
