# Generated by Django 3.0.5 on 2022-01-10 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_conversionrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversionrate',
            name='conversion_rate',
            field=models.FloatField(verbose_name='Conversion Rate Value in INR '),
        ),
    ]
