# Generated by Django 3.0.5 on 2022-01-12 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20220110_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_table',
            name='activate_hash',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
