# Generated by Django 3.0.5 on 2022-01-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_table_activate_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthStones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='birthstones/')),
                ('name', models.CharField(max_length=30, verbose_name='Stone Name')),
                ('month', models.CharField(max_length=30, verbose_name='Month')),
                ('about', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Birth Stones',
            },
        ),
    ]
