# Generated by Django 3.0.5 on 2021-12-07 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20211205_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribed_users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=90)),
            ],
        ),
    ]
