# Generated by Django 3.0.5 on 2022-01-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_birthstones'),
    ]

    operations = [
        migrations.RenameField(
            model_name='birthstones',
            old_name='about',
            new_name='description',
        ),
        migrations.AddField(
            model_name='birthstones',
            name='tagline',
            field=models.CharField(default='Ruby is this of this', max_length=30, verbose_name='Tagline'),
            preserve_default=False,
        ),
    ]
