# Generated by Django 3.0.5 on 2022-01-12 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20220112_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_table',
            name='state',
        ),
    ]
