# Generated by Django 3.0.5 on 2022-01-13 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_delete_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribed_users',
            options={'verbose_name_plural': 'Subscribed Users'},
        ),
    ]
