# Generated by Django 3.0.5 on 2022-01-16 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20220115_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthstones',
            name='tagline',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Tagline'),
        ),
    ]
